---
# tasks file for reverse-proxy
- name: Add {{ user.name }} to docker group
  user: name='{{ user.name }}'
        groups=docker
        append=yes

# 1. Create folders
- name: Create folder for reverse-proxy configuration
  file:
    path="{{ item }}"
    state=directory
  with_items:
    - "/home/{{ user.name }}/reverse-proxy/"
    - "/home/{{ user.name }}/reverse-proxy/certs"
    - "/home/{{ user.name }}/reverse-proxy/htpasswd"
    - "/home/{{ user.name }}/reverse-proxy/vhost.d"

- name: Get latest nginx.tmpl
  get_url:
    url:  https://raw.githubusercontent.com/jwilder/nginx-proxy/master/nginx.tmpl
    dest: /home/{{ user.name }}/reverse-proxy/nginx.tmpl

# 2. Special configuration
- include: my_specialconfs.yml

# 3. Docker contener
- name: reverse-proxy docker setup
  docker_container:
    name: reverse-proxy
    image: nginx
    state: started
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/home/{{ user.name }}/reverse-proxy/certs:/etc/nginx/certs:ro"
      - "/home/{{ user.name }}/reverse-proxy/vhost.d:/etc/nginx/vhost.d"
      - "/home/{{ user.name }}/reverse-proxy/htpasswd:/etc/nginx/htpasswd:ro"
      - "/usr/share/nginx/html"
      - "/etc/nginx/conf.d"

- name: docker-gen image
  docker_container:
    name: reverse-proxy-gen
    image: jwilder/docker-gen
    state: started
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/home/{{ user.name }}/reverse-proxy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - reverse-proxy
    command: "-notify-sighup reverse-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"

- name: reverse-proxy letsencrypt companion setup
  docker_container:
    name: reverse-proxy-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    state: started
    volumes:
      - "/home/{{ user.name }}/reverse-proxy/certs:/etc/nginx/certs:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - reverse-proxy
    env:
      NGINX_DOCKER_GEN_CONTAINER: reverse-proxy-gen
