---
# tasks file for reverse-proxy
- name: Add {{ user.name }} to docker group
  user: name='{{ user.name }}'
        groups=docker
        append=yes

# 1. Create folders
- name: Create folder for reverse-proxy configuration
  file:
    path="{{ item }}"
    state=directory
  with_items:
    - "/home/{{ user.name }}/reverse-proxy/"
    - "/home/{{ user.name }}/reverse-proxy/certs"
    - "/home/{{ user.name }}/reverse-proxy/htpasswd"
    - "/home/{{ user.name }}/reverse-proxy/vhost.d"

# 2. Special configuration
# Copy crt, configuration files, htpasswords... for each of the desired services
# The certs and htpassword should be already generated and are uploaded directly to the
# host machine. Then you simply mount folders on the reverse-proxy docker contener.
- include: my_specialconfs.yml

# 3. Docker contener
- name: reverse-proxy docker setup
  docker_container:
    name: reverse-proxy
    image: jwilder/nginx-proxy
    state: started
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "/home/{{ user.name }}/reverse-proxy/certs:/etc/nginx/certs:ro"
    - "/home/{{ user.name }}/reverse-proxy/vhost.d:/etc/nginx/vhost.d"
    - "/home/{{ user.name }}/reverse-proxy/htpasswd:/etc/nginx/htpasswd:ro"
    - "/usr/share/nginx/html"
    - "/var/run/docker.sock:/tmp/docker.sock:ro"

- name: reverse-proxy letsencrypt companion setup
  docker_container:
    name: reverse-proxy-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    state: started
    volumes:
    - "/home/{{ user.name }}/reverse-proxy/certs:/etc/nginx/certs:rw"
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
    - reverse-proxy
