- name: Gogs configuration
  template:
    src="templates/your-site.com"
    dest="/home/{{ user.name }}/reverse-proxy/vhost.d/your-site.com"
    owner=root
    mode=0755

- name: Auth for cadvisor configuration
  template:
    src="templates/your-site.com.j2"
    dest="/home/{{ user.name }}/reverse-proxy/htpasswd/your-site.com.fr"
    owner={{ user.name }}
    mode=0755
