---
# tasks file for collectd
- name: Install collectd
  apt: >
    name={{ item }}
    state=present
  with_items:
    - collectd=5.7.0-3~bpo8+1
    - collectd-core=5.7.0-3~bpo8+1
    - collectd-utils=5.7.0-3~bpo8+1

- name: Configure collectd
  template: >
    src="templates/collectd.conf.j2"
    dest="/etc/collectd/collectd.conf"
  notify:
    restart collectd
