---
# tasks file for gogs
- name: Ensure that gogs home exists
  file: path=/home/gogs state=directory

- name: Create docker mysql database
  docker_container:
    name: gogs-db
    image: tutum/mysql
    state: started
    env:
      ON_CREATE_DB: "gogs"
      MYSQL_USER: gogs
      MYSQL_PASS: gogs

- name: gogs docker setup
  docker_container:
    name: gogs
    image: gogs/gogs
    state: started
    links:
    - "gogs-db:gogs-db"
    volumes:
    - "/home/gogs:/data"
    env:
      VIRTUAL_PORT: 3000
      VIRTUAL_HOST: "{{ hosts.gogs }}"
