---
# tasks file for file-streaming
- name: Create special conf folder for file streaming
  file: path="/home/{{ user.name }}/file-streaming/" state=directory

- name: Special conf for h5ai
  template:
    src="templates/{{ item }}.j2"
    dest="/home/{{ user.name }}/file-streaming/{{ item }}"
  with_items:
    - h5ai-special.conf
    - options.json

- name: "{{ files.master }} docker setup"
  docker_container:
    name: "{{ files.master }}"
    image: clue/h5ai
    state: started
    volumes:
    - "/rtorrent/finished/:/var/www"
    - "/home/{{ user.name }}/file-streaming/h5ai-special.conf:/etc/nginx/sites-available/h5ai"
    - "/home/{{ user.name }}/file-streaming/options.json:/usr/share/h5ai/_h5ai/conf/options.json"
    env:
      VIRTUAL_HOST: "{{ hosts.files.master }}"
      LETSENCRYPT_HOST: "{{ hosts.files.master }}"
      LETSENCRYPT_EMAIL: "{{ letsencrypt.email }}"
      ALLOW_OVERRIDE: true

- name: "{{ files.slaves.first }} docker setup"
  docker_container:
    name: "{{ files.slaves.first }}"
    image: clue/h5ai
    state: started
    volumes:
    - "/rtorrent2/finished/:/var/www"
    - "/home/{{ user.name }}/file-streaming/h5ai-special.conf:/etc/nginx/sites-available/h5ai"
    - "/home/{{ user.name }}/file-streaming/options.json:/usr/share/h5ai/_h5ai/conf/options.json"
    env:
      VIRTUAL_HOST: "{{ hosts.files.first }}"
      LETSENCRYPT_HOST: "{{ hosts.files.first }}"
      LETSENCRYPT_EMAIL: "{{ letsencrypt.email }}"
      ALLOW_OVERRIDE: true

- name: "{{ files.slaves.second }} docker setup"
  docker_container:
    name: "{{ files.slaves.second }}"
    image: clue/h5ai
    state: started
    volumes:
    - "/rtorrent3/finished/:/var/www"
    - "/home/{{ user.name }}/file-streaming/h5ai-special.conf:/etc/nginx/sites-available/h5ai"
    - "/home/{{ user.name }}/file-streaming/options.json:/usr/share/h5ai/_h5ai/conf/options.json"
    env:
      VIRTUAL_HOST: "{{ hosts.files.second }}"
      LETSENCRYPT_HOST: "{{ hosts.files.second }}"
      LETSENCRYPT_EMAIL: "{{ letsencrypt.email }}"
      ALLOW_OVERRIDE: true

- name: "{{ files.slaves.third }} docker setup"
  docker_container:
    name: "{{ files.slaves.third }}"
    image: clue/h5ai
    state: started
    volumes:
    - "/rtorrent4/finished/:/var/www"
    - "/home/{{ user.name }}/file-streaming/h5ai-special.conf:/etc/nginx/sites-available/h5ai"
    - "/home/{{ user.name }}/file-streaming/options.json:/usr/share/h5ai/_h5ai/conf/options.json"
    env:
      VIRTUAL_HOST: "{{ hosts.files.third }}"
      LETSENCRYPT_HOST: "{{ hosts.files.third }}"
      LETSENCRYPT_EMAIL: "{{ letsencrypt.email }}"
      ALLOW_OVERRIDE: true
