---
# tasks file for newrelic-srv
- name: Add repos for the newrelic agent
  template: 
    src: "templates/newrelic.list.j2"
    dest: "/etc/apt/sources.list.d/newrelic.list"
    owner: root
    mode: 777

- name: Trust the New Relic GPG key
  apt_key:
    url: "https://download.newrelic.com/548C16BF.gpg"
    state: present

- name: Update apt
  apt: update_cache=yes

- name: Install newrelic agent
  apt: name=newrelic-sysmond state=installed

- name: Add key to newrelic agent
  command: nrsysmond-config --set license_key={{ license_newrelic }}

- name: Start newrelic agent
  service: name=newrelic-sysmond state=started