---
# tasks file for seedbox
- name: Special conf for "{{ h5ai_name }}"
  template:
    src="templates/{{ item }}.j2"
    dest="{{ srv_root }}/{{ item }}"
  with_items:
    - h5ai-special.conf
    - options.json

- name: Ensure that directories needed for seedbox "{{ seedbox_name }}" exist
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    recurse: yes
  with_items:
    - "{{ srv_root }}"
    - "{{ srv_root }}/finished"

- name: htpasswd for seedbox "{{ seedbox_name }}" configuration
  template:
    src: "templates/{{ host_seedbox }}.j2"
    dest: "/rtorrent/finished/.htpasswd"
    owner: www-data
    group: www-data

- name: Remove lock to allow several seedbox to run at the same time
  file:
    path: "{{ srv_root }}/.session/rtorrent.lock"
    state: absent
  become: yes
  become_user: root
  become_method: sudo

- name: Create docker conteners for seedbox "{{ seedbox_name }}"
  docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: started
    interactive: yes
    privileged: yes
    user: root:root
    force_kill: yes
    restart_policy: always
    dns_servers: 8.8.8.8
    ports:
      - "{{ ports_up }}"
      - "{{ ports_down }}"
    volumes:
      - "{{ srv_root }}/finished/.htpasswd:/usr/share/nginx/html/rutorrent/.htpasswd"
      - "{{ srv_root }}:/rtorrent"
    env:
      LETSENCRYPT_HOST: "{{ letsencrypt_host }}"
      LETSENCRYPT_EMAIL: "{{ letsencrypt_email }}"
      LOGSPOUT: ignore
      TERM: xterm
      UPLOAD_RATE: 0
      VIRTUAL_HOST: "{{ host_seedbox }}"
  with_items:
    - { name: "{{ seedbox_name }}", image: "kfei/docktorrent" }

- name: "{{ h5ai_name }} docker setup"
  docker_container:
    name: "{{ h5ai_name }}"
    image: clue/h5ai
    state: started
    volumes:
    - "{{ srv_root }}/finished/:/var/www"
    - "{{ srv_root }}/h5ai-special.conf:/etc/nginx/sites-available/h5ai"
    - "{{ srv_root }}/options.json:/usr/share/h5ai/_h5ai/conf/options.json"
    env:
      VIRTUAL_HOST: "{{ h5ai_host }}"
      LETSENCRYPT_HOST: "{{ h5ai_host }}"
      LETSENCRYPT_EMAIL: "{{ letsencrypt_email }}"
      ALLOW_OVERRIDE: true
