---
# tasks file for seedbox
# 1. Create folders to store files
# For master and slave seedbox
- name: Ensure that directories needed exist
  file: 
    path="{{ item }}"
    state=directory
  with_items:
    - "/rtorrent"
    - "/rtorrent/finished"
    - "/rtorrent2"    
    - "/rtorrent2/finished"
    - "/rtorrent3"
    - "/rtorrent3/finished"

# 2. Copy .htpasswd files
- include: my_specialconfs.yml

# 3. Cleanup: remove existing docker conteners
- name: Remove docker conteners if exist
  docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: absent
  with_items:
    - { name: '{{ seedbox_master.name }}', image: 'kfei/docktorrent' }
    - { name: '{{ seedbox_slaves.names.first }}', image: 'kfei/docktorrent' }    
    - { name: '{{ seedbox_slaves.names.second }}', image: 'kfei/docktorrent' }
  become: yes
  become_user: root
  become_method: sudo
  retries: 5

# Chill out mate
- name: pause execution to chill a bit
  pause: seconds=30

- name: Wipe existing screen
  command: "{{ item }}"
  ignore_errors: yes
  become: yes
  become_user: "{{ user.name }}"
  with_items:
    - "screen -ls | grep pts | cut -d. -f1 | awk '{print $1}' | xargs kill"
    - "screen -wipe"
  retries: 5  

# 4. First seedbox
- name: Remove lock to allow several seedbox to run at the same time
  file:
    path: /rtorrent/.session/rtorrent.lock
    state: absent
  become: yes
  become_user: root
  become_method: sudo

# Dirty turnaround: launch a seedbox on a detached screen...
- name: "{{ seedbox_master.name }} setup"
  command: "screen -dmS {{ seedbox_master.name }} bash -c 'docker run -it -p {{ seedbox_master.ports.dl }} --restart=always -p {{ seedbox_master.ports.up }} --dns 8.8.8.8 -e UPLOAD_RATE=0 -v /rtorrent/:/rtorrent -v /rtorrent/finished/.htpasswd:/usr/share/nginx/html/rutorrent/.htpasswd -e VIRTUAL_HOST={{ hosts.seedbox_master }} -e UPLOAD_RATE=0 --name {{ seedbox_master.name }} kfei/docktorrent'"
  become: yes
  become_user: "{{ user.name }}"

# 5. Second seedbox...
- name: Remove lock to allow several seedbox to run at the same time
  file:
    path: /rtorrent2/.session/rtorrent.lock
    state: absent
  become: yes
  become_user: root
  become_method: sudo

- name: "{{ seedbox_slaves.names.first }} setup"
  command: "screen -dmS {{ seedbox_slaves.names.first }} bash -c 'docker run -it -p {{ seedbox_slaves.ports.first }} --restart=always --dns 8.8.8.8 -e UPLOAD_RATE=0 -v /rtorrent2/:/rtorrent -v /rtorrent2/finished/.htpasswd:/usr/share/nginx/html/rutorrent/.htpasswd -e VIRTUAL_HOST={{ hosts.seedbox_slaves.first }} -e UPLOAD_RATE=0 --name {{ seedbox_slaves.names.first }} kfei/docktorrent'"
  become: yes
  become_user: "{{ user.name }}"

  # 6. Third seedbox...
- name: Remove lock to allow several seedbox to run at the same time
  file:
    path: /rtorrent3/.session/rtorrent.lock
    state: absent
  become: yes
  become_user: root
  become_method: sudo

- name: "{{ seedbox_slaves.names.second }} setup"
  command: "screen -dmS {{ seedbox_slaves.names.second }} bash -c 'docker run -it -p {{ seedbox_slaves.ports.second }} --restart=always --dns 8.8.8.8 -e UPLOAD_RATE=0 -v /rtorrent3/:/rtorrent -v /rtorrent3/finished/.htpasswd:/usr/share/nginx/html/rutorrent/.htpasswd -e VIRTUAL_HOST={{ hosts.seedbox_slaves.second }} -e UPLOAD_RATE=0 --name {{ seedbox_slaves.names.second }} kfei/docktorrent'"
  become: yes
  become_user: "{{ user.name }}"
