- name: htpasswd for master seedbox configuration
  template: 
    src="templates/your-htpwd.j2" # CHANGEME
    dest="/rtorrent/finished/.htpasswd"
    mode=777

- name: htpasswd for first slave configuration
  template: 
    src="templates/your-htpwd.j2" # CHANGEME
    dest="/rtorrent2/finished/.htpasswd"
    mode=777
