---
- name: Ensure directory created
  file: path={{ item }} state=directory
  with_items:
    - "/home/owncloud"
    - "/home/owncloud/apps"
    - "/home/owncloud/config"
    - "/home/owncloud/data"
    - "/home/{{ user.name }}/backup"

# Restore previous version of database if any.
- name: Owncloud db configuration
  template: 
    src="templates/backup.sql.j2"
    dest="/home/{{ user.name }}/backup/backup.sql"
  ignore_errors: yes

- name: Create docker owncloud mysql database
  docker_container:
    name: db-owncloud
    image: mariadb
    state: started
    env:
      MYSQL_ROOT_PASSWORD: "{{ db_owncloud_pwd }}"
    volumes:
      - "/home/{{ user.name }}/backup/:/docker-entrypoint-initdb.d/"

- name: Create docker owncloud
  docker_container:
    name: owncloud
    image: owncloud
    links:
    - "db-owncloud:db-owncloud"
    state: started
    volumes:
    - "/home/owncloud/apps:/var/www/html/apps"
    - "/home/owncloud/config:/var/www/html/config"
    - "/home/owncloud/data:/var/www/html/data"
    env:
      VIRTUAL_HOST: "{{ hosts.owncloud }}"

# Backup SQL database every hour.
- name: Create the backup contener for database
  docker_container:
    name: owncloud-db-backup
    image: hauptmedia/mariadb-backup
    links:
      - "db-owncloud:db-owncloud"
    state: started
    volumes:
      - "/rtorrent/finished/:/var/backups"
    env:
      VIRTUAL_HOST: "{{ hosts.owncloud_backup }}"
      VIRTUAL_PORT: 18080
      TIMEZONE: "Europe/Paris"
      SCHEDULE: "30 * * * *"
      BACKUP_METHOD: "mysqldump"
      BACKUP_OPTS: "-u root -p {{ db_owncloud_pwd }} -h db-owncloud -d /var/backups/owncloud-db-backup.sql"

# Include special conf to upload the backups created by the docker contener in owncloud itself :-)
- include: my_specialconfs.yml 

