---
- name: Ensure directory created
  file: path={{ item }} state=directory
  with_items:
    - "/home/owncloud"
    - "/home/owncloud/apps"
    - "/home/owncloud/config"
    - "/home/owncloud/data"
    - "/tmp/backup/"

# Restore previous version of database if any.
- name: ownCloud db configuration
  template:
    src="templates/backup.sql.j2"
    dest="/tmp/backup/backupOwncloud.sql"
  ignore_errors: yes

- name: Create docker ownCloud mysql database
  docker_container:
    name: owncloud-db
    image: mariadb
    state: started
    env:
      MYSQL_ROOT_PASSWORD: "{{ owncloud_db_pwd }}"
    volumes:
      - "/tmp/backup/:/docker-entrypoint-initdb.d/"

- name: Create docker ownCloud
  docker_container:
    name: owncloud
    image: owncloud
    links:
    - "owncloud-db:owncloud-db"
    state: started
    expose:
      - "80:80"
    volumes:
    - "/home/owncloud/apps:/var/www/html/apps"
    - "/home/owncloud/config:/var/www/html/config"
    - "/home/owncloud/data:/var/www/html/data"
    env:
      VIRTUAL_HOST: "{{ hosts.owncloud }}"

# Backup SQL database every hour.
- name: Create the backup contener for database
  docker_container:
    name: owncloud-db-backup
    image: hauptmedia/mariadb-backup
    links:
      - "owncloud-db:owncloud-db"
    state: started
    volumes:
      - "/rtorrent/finished/:/var/backups"
    env:
      VIRTUAL_HOST: "{{ hosts.owncloud_backup }}"
      VIRTUAL_PORT: 18080
      TIMEZONE: "Europe/Paris"
      SCHEDULE: "30 * * * *"
      BACKUP_METHOD: "mysqldump"
      BACKUP_OPTS: "-u root -p {{ owncloud_db_pwd }} -h owncloud-db -d /var/backups/owncloud-db-backup.sql"

# Include special conf to upload the backups created by the docker contener in owncloud itself :-)
- include: my_specialconfs.yml
