---
# tasks file for file-streaming
- name: Create special conf folder for file streaming
  file:
    path="/home/{{ user.name }}/file-streaming/"
    state=directory
    mode=777

- name: Special conf for server
  template:
    src="templates/h5ai-special.conf.j2"
    dest="/home/{{ user.name }}/file-streaming/h5ai-special.conf"
    owner=root
    mode=777

- name: Special conf for file streaming
  template:
    src="templates/options.json.j2"
    dest="/home/{{ user.name }}/file-streaming/options.json"
    owner=root
    mode=777

- name: "{{ files.master }} docker setup"
  docker_container:
    name: "{{ files.master }}"
    image: smdion/docker-h5ai
    state: started
    expose:
    - 443
    volumes:
    - "/rtorrent/finished/:/var/www"
    - "/home/{{ user.name }}/file-streaming/h5ai-special.conf:/etc/nginx/sites-available/h5ai"
    - "/home/{{ user.name }}/file-streaming:/config"
    env:
      VIRTUAL_HOST: "{{ hosts.files.master }}"
      LETSENCRYPT_HOST: "{{ hosts.files.master }}"
      LETSENCRYPT_EMAIL: "{{ letsencrypt.email }}"
      VIRTUAL_PORT: 443
      ALLOW_OVERRIDE: true

- name: "{{ files.slaves.first }} docker setup"
  docker_container:
    name: "{{ files.slaves.first }}"
    image: smdion/docker-h5ai
    state: started
    expose:
    - 443
    volumes:
    - "/rtorrent2/finished/:/var/www"
    - "/home/{{ user.name }}/file-streaming/h5ai-special.conf:/etc/nginx/sites-available/h5ai"
    - "/home/{{ user.name }}/file-streaming:/config"
    env:
      VIRTUAL_HOST: "{{ hosts.files.first }}"
      LETSENCRYPT_HOST: "{{ hosts.files.first }}"
      LETSENCRYPT_EMAIL: "{{ letsencrypt.email }}"
      VIRTUAL_PORT: 443
      ALLOW_OVERRIDE: true

- name: "{{ files.slaves.second }} docker setup"
  docker_container:
    name: "{{ files.slaves.second }}"
    image: smdion/docker-h5ai
    state: started
    expose:
    - 443
    volumes:
    - "/rtorrent3/finished/:/var/www"
    - "/home/{{ user.name }}/file-streaming/h5ai-special.conf:/etc/nginx/sites-available/h5ai"
    - "/home/{{ user.name }}/file-streaming:/config"
    env:
      VIRTUAL_HOST: "{{ hosts.files.second }}"
      LETSENCRYPT_HOST: "{{ hosts.files.second }}"
      LETSENCRYPT_EMAIL: "{{ letsencrypt.email }}"
      VIRTUAL_PORT: 443
      ALLOW_OVERRIDE: true

- name: "{{ files.slaves.third }} docker setup"
  docker_container:
    name: "{{ files.slaves.third }}"
    image: smdion/docker-h5ai
    state: started
    expose:
    - 443
    volumes:
    - "/rtorrent4/finished/:/var/www"
    - "/home/{{ user.name }}/file-streaming/h5ai-special.conf:/etc/nginx/sites-available/h5ai"
    - "/home/{{ user.name }}/file-streaming:/config"
    env:
      VIRTUAL_HOST: "{{ hosts.files.third }}"
      LETSENCRYPT_HOST: "{{ hosts.files.third }}"
      LETSENCRYPT_EMAIL: "{{ letsencrypt.email }}"
      VIRTUAL_PORT: 443
      ALLOW_OVERRIDE: true
